

github:
  description: "Apache Hive"
  homepage: https://hive.apache.org/
  labels:
    - hive
    - java
    - database
    - sql
    - apache
    - big-data
    - hadoop
  features:
    wiki: false
    issues: false
    projects: false
  enabled_merge_buttons:
    squash:  true
    merge:   true
    rebase:  true
notifications:
  commits:      commits@hive.apache.org
  pullrequests: dev@hive.apache.org
  jira_options: link label worklog
