#!/bin/bash -e

export MAVEN_OPTS="-Xmx2g"
export M_OPTS="-Dmaven.test.failure.ignoreX -fae -Dtest.groups= -Pitests,qsplits -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugin.surefire.SurefirePlugin=INFO"


#head -n1111 /proc/cpuinfo /proc/meminfo

set -x

case "$1" in
	build)
		echo "@ build"
		mvn $M_OPTS -B install -DskipTests
	;;
	test)
		M=$3
		i=$2
		echo "@ tests $i / $M"
		#time mvn $M_OPTS -q generate-sources -Pitests,qsplits
		time mvn $M_OPTS -q install -DskipTests
		find . -name Test*.java |
			sed 's|.*org/apache/|org/apache/|'|
			sort -R --random-source=<(yes) |
			awk "NR % $M == $i" > tests
		wc -l tests
		head tests
		mvn $M_OPTS -q install surefire-report:report -Dsurefire.includesFile=$PWD/tests
	;;
	*)
		echo "unknown $?"
		exit 1
	;;
esac


