name: CI

on:
  pull_request:
    branches:
      - '*'
jobs:
  split0:
    name: 'split0'
    runs-on: ubuntu-latest
    env:
      M_OPTS: -Dmaven.test.failure.ignore -Dtest.groups= -Pitests,qsplits -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugin.surefire.SurefirePlugin=INFO
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'build'
        run: time mvn $M_OPTS -B install -DskipTests
      - run: find . -name Test*.class | sed 's|.*org/apache/|org/apache/|'| sort -R --random-source=<(yes) | awk 'NR % 100 == 0' > tests
      - run: wc -l tests
      - run: head tests
      - run: time mvn $M_OPTS -q install -Dsurefire.includesFile=tests 

