name: CI

on:
  pull_request:
    branches:
      - '*'
jobs:
  split0:
    name: 'split0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'build'
        run: |
           mvn -B install -DskipTests -Pitests,qsplits
      - run: find . -name Test*.class | sort -R --random-source=<(yes) | awk 'NR % 50 == 0' > tests
           
